// Autogenerated from Pigeon (v3.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class HJSetLicenceMessage;

@interface HJSetLicenceMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithUrl:(NSString *)url
    key:(NSString *)key;
@property(nonatomic, copy) NSString * url;
@property(nonatomic, copy) NSString * key;
@end

/// The codec used by HJLiveBaseApi.
NSObject<FlutterMessageCodec> *HJLiveBaseApiGetCodec(void);

@protocol HJLiveBaseApi
- (void)setLicenceMsg:(HJSetLicenceMessage *)msg error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void HJLiveBaseApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HJLiveBaseApi> *_Nullable api);

NS_ASSUME_NONNULL_END
