// Autogenerated from Pigeon (v3.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "LiveBaseMessages.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface HJSetLicenceMessage ()
+ (HJSetLicenceMessage *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation HJSetLicenceMessage
+ (instancetype)makeWithUrl:(NSString *)url
    key:(NSString *)key {
  HJSetLicenceMessage* pigeonResult = [[HJSetLicenceMessage alloc] init];
  pigeonResult.url = url;
  pigeonResult.key = key;
  return pigeonResult;
}
+ (HJSetLicenceMessage *)fromMap:(NSDictionary *)dict {
  HJSetLicenceMessage *pigeonResult = [[HJSetLicenceMessage alloc] init];
  pigeonResult.url = GetNullableObject(dict, @"url");
  NSAssert(pigeonResult.url != nil, @"");
  pigeonResult.key = GetNullableObject(dict, @"key");
  NSAssert(pigeonResult.key != nil, @"");
  return pigeonResult;
}
- (NSDictionary *)toMap {
  return @{
    @"url" : (self.url ?: [NSNull null]),
    @"key" : (self.key ?: [NSNull null]),
  };
}
@end

@interface HJLiveBaseApiCodecReader : FlutterStandardReader
@end
@implementation HJLiveBaseApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [HJSetLicenceMessage fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface HJLiveBaseApiCodecWriter : FlutterStandardWriter
@end
@implementation HJLiveBaseApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[HJSetLicenceMessage class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface HJLiveBaseApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation HJLiveBaseApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[HJLiveBaseApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[HJLiveBaseApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *HJLiveBaseApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    HJLiveBaseApiCodecReaderWriter *readerWriter = [[HJLiveBaseApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void HJLiveBaseApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HJLiveBaseApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.LiveBaseApi.setLicence"
        binaryMessenger:binaryMessenger
        codec:HJLiveBaseApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setLicenceMsg:error:)], @"HJLiveBaseApi api (%@) doesn't respond to @selector(setLicenceMsg:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        HJSetLicenceMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setLicenceMsg:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
