// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class HJLivePusherMessage;
@class HJStartMessage;

@interface HJLivePusherMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * pusherId;
@end

@interface HJStartMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * pusherId;
@property(nonatomic, copy, nullable) NSString * url;
@end

/// The codec used by HJLivePusherApi.
NSObject<FlutterMessageCodec> *HJLivePusherApiGetCodec(void);

@protocol HJLivePusherApi
- (nullable HJLivePusherMessage *)createWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)startPushMsg:(HJStartMessage *)msg error:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopPushMsg:(HJLivePusherMessage *)msg error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeMsg:(HJLivePusherMessage *)msg error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void HJLivePusherApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HJLivePusherApi> *_Nullable api);

NS_ASSUME_NONNULL_END
