// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "LivePusherMessages.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface HJLivePusherMessage ()
+ (HJLivePusherMessage *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface HJStartMessage ()
+ (HJStartMessage *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation HJLivePusherMessage
+ (HJLivePusherMessage *)fromMap:(NSDictionary *)dict {
  HJLivePusherMessage *result = [[HJLivePusherMessage alloc] init];
  result.pusherId = dict[@"pusherId"];
  if ((NSNull *)result.pusherId == [NSNull null]) {
    result.pusherId = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.pusherId ? self.pusherId : [NSNull null]), @"pusherId", nil];
}
@end

@implementation HJStartMessage
+ (HJStartMessage *)fromMap:(NSDictionary *)dict {
  HJStartMessage *result = [[HJStartMessage alloc] init];
  result.pusherId = dict[@"pusherId"];
  if ((NSNull *)result.pusherId == [NSNull null]) {
    result.pusherId = nil;
  }
  result.url = dict[@"url"];
  if ((NSNull *)result.url == [NSNull null]) {
    result.url = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.pusherId ? self.pusherId : [NSNull null]), @"pusherId", (self.url ? self.url : [NSNull null]), @"url", nil];
}
@end

@interface HJLivePusherApiCodecReader : FlutterStandardReader
@end
@implementation HJLivePusherApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [HJLivePusherMessage fromMap:[self readValue]];
    
    case 129:     
      return [HJStartMessage fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface HJLivePusherApiCodecWriter : FlutterStandardWriter
@end
@implementation HJLivePusherApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[HJLivePusherMessage class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[HJStartMessage class]]) {
    [self writeByte:129];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface HJLivePusherApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation HJLivePusherApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[HJLivePusherApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[HJLivePusherApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *HJLivePusherApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    HJLivePusherApiCodecReaderWriter *readerWriter = [[HJLivePusherApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void HJLivePusherApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HJLivePusherApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.LivePusherApi.create"
        binaryMessenger:binaryMessenger
        codec:HJLivePusherApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createWithError:)], @"HJLivePusherApi api (%@) doesn't respond to @selector(createWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        HJLivePusherMessage *output = [api createWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.LivePusherApi.startPush"
        binaryMessenger:binaryMessenger
        codec:HJLivePusherApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startPushMsg:error:)], @"HJLivePusherApi api (%@) doesn't respond to @selector(startPushMsg:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        HJStartMessage *arg_msg = args[0];
        FlutterError *error;
        [api startPushMsg:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.LivePusherApi.stopPush"
        binaryMessenger:binaryMessenger
        codec:HJLivePusherApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopPushMsg:error:)], @"HJLivePusherApi api (%@) doesn't respond to @selector(stopPushMsg:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        HJLivePusherMessage *arg_msg = args[0];
        FlutterError *error;
        [api stopPushMsg:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.LivePusherApi.dispose"
        binaryMessenger:binaryMessenger
        codec:HJLivePusherApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disposeMsg:error:)], @"HJLivePusherApi api (%@) doesn't respond to @selector(disposeMsg:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        HJLivePusherMessage *arg_msg = args[0];
        FlutterError *error;
        [api disposeMsg:arg_msg error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
